# -*- coding: utf-8 -*-
"""YS_31_32_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ozvbVNAeIHgocR7ljx4ImZt9lVlxOVu3
"""

# int
x = 99
print(type(x))

# None

x = None
print(type(x))

# float

a = 3.5
print(type(a))

# bool (EXAMPLE)

lights = False
print(type(lights))

# Sequence

name = "Yashar"
print(type(name))

# List

newList = [1, 2, 3, 4, 5]
print(newList)
stringList = ["John", "billy", "Thomas", "Lg smart fridge"]
print(stringList)

# Tuple

newTuple = ("List", "Tuple")
print(newTuple)

# Dictionary

newDictionary = {"Day" : "Friday", True : True,}

print(newDictionary)

# Calculator

a = float(input("Input a number (+ the other number)"))

b = float(input("Input another number (+ the other number)"))

c = a + b

print("Your number + the other is", a + b)

d = a * b

print("Your number times the other is", d)

e = a / b

print("Your number divided by the other is", e)

f = a - b

print("Your number subtracted by the other is", f)